feat: Projects Overview creation
xnd-dev/ipas pull request #11
Opened 2023-07-04 23:02 UTC by Felipee-M

## Purpose

Creation of the projects overview section.

## Approach and changes

Creation and stylization of the projects overview section

## Definition of done

- [x] Behavior reviewed
- [x] Development completed
- [x] Reviewers assigned

2023-07-05 16:43 UTC, xnd-dev submitted a review, later dismissed
lgtm

2023-07-07 07:46 UTC, Derecky requested changes
Mandou muito bem, @Felipee-M, apontei só algumas coisas, não são necessariamente erros.

2023-07-07 07:46 UTC, Derecky commented on src/components/projects-overview/projects-overview.tsx
> +            <h1>Nossos Projetos Sociais:</h1>
Só cuidado com esse h1 aqui, só pode existir um único h1 por página, e acionais já tem em outra sessão.

2023-07-07 07:46 UTC, Derecky commented on src/components/projects-overview/projects-overview.tsx
> +                  alegria, apoio e solidariedade para aqueles que mais precisam.{' '}
Esse espaçamento no final, é necessário?

2023-07-07 07:46 UTC, Derecky commented on src/components/projects-overview/projects-overview.tsx
> +                  <br />
Porque a necessidade do `<br />`?

2023-07-07 07:46 UTC, Derecky commented on src/components/projects-overview/projects-overview.tsx
> +                <Image src={ImageProject2} alt="" sizes="100vw" />
Imagem é sempre bom ter um texto alternativo, pergunta pra UX ou PM qual por, eles são os responsáveis por acessibilidade e também se responsabilizam para caso não haja acessibilidade

2023-07-07 07:46 UTC, Derecky commented on src/components/projects-overview/projects-overview.tsx
> +import ImageProject2 from '../../../public/acvolun.png'
O nome dessas imagens podem ser melhor descritivas, para hora de dar manutenção, caso altere uma, fica difícil achar em qual dar manutenção caso aumente imagens também.

2023-07-07 07:46 UTC, Derecky commented on src/components/projects-overview/projects-overview.tsx
> +} from './projects-overview.styles'
Esse aqui, o @xnd-dev consegue lhe dar um help, não está errado, é só uma boa pratica juntar isso no import

2023-07-07 07:46 UTC, Derecky commented on src/components/projects-overview/projects-overview.tsx
> +                  <br />
Pra você evitar estar chamando esse breakLine sempre, você pode usar o display flex no container e definir-nos-emos flex direction como column no css:

```Javascript
display: "flex"
flexDirection: "column"
```

2023-07-07 07:46 UTC, Derecky commented on src/styles/globals.ts
> +    fontFamily: 'Poppins, sans-serif',
Todas as fontes dessas tags, no projeto será poppins? Caso não, isso pode quebrar o layout de outros commits

2023-07-07 07:47 UTC, Derecky commented
@Felipee-M quando der, coloca aqui a screenshot do que foi feito, pra ajudar quando for analisar com o protótipo

2023-07-11 18:17 UTC, Felipee-M commented on src/components/projects-overview/projects-overview.tsx
> +                  alegria, apoio e solidariedade para aqueles que mais precisam.{' '}
Estranho, pq no meu código não aparece esse espaçamento, só coloquei o br mesmo.

2023-07-11 18:25 UTC, Felipee-M commented on src/components/projects-overview/projects-overview.tsx
> +                  <br />
É pq eu tinha visto lá no figma de um jeito e quis simular igual, ai acabei usando o br pra ter o mesmo aspecto, mas eu vi aqui que só por eles estarem em tags <p> distintas eles ficam no aspecto que eu queria, ai removi o <br />

2023-07-11 18:26 UTC, Felipee-M commented on src/components/projects-overview/projects-overview.tsx
> +                  <br />
removi o br*

2023-07-13 12:54 UTC, Derecky approved these changes
lgtm

2023-07-13 15:22 UTC, merged