Slider
xnd-dev/ipas pull request #12
Opened 2023-07-06 21:37 UTC by xnd-dev

## Purpose

Add the slider to the project

## Approach and changes

Creation of the Slider Section

## Definition of done

- [x] Behavior reviewed
- [x] Development completed
- [x] Reviewers assigned

## Screenshots
![image](https://github.com/xnd-dev/ipas/assets/102488612/e279d8dc-cfe2-4186-b24d-eace5fbe30d3)

2023-07-06 21:55 UTC, Felipee-M approved these changes, later dismissed
Nothing to add.

2023-07-07 07:25 UTC, Derecky requested changes
Deixei alguns pontos de melhorias, e só uma correção. Dá uma olhada aí e qualquer coisa me dá um retorno o/

2023-07-07 07:25 UTC, Derecky commented on src/components/slider/Carousel.tsx
> +    if (delta < 0 && activeIndex < slidesData.length - 1) {
Esse delta aqui não serve pra nada a ideia é boa, mas a aplicabilidade não, porque deixa a legibilidade ruim, você entende porque fez esse código, mas tu acha que uma pessoa começando entenderia? 

Você pode fazer um enum

```Javascript
enum UPDATE_COUNT {
  INCREMENT, DECREMENT
}
```

E verificar se é increment ou decrement na função e operar 

Porque isso ajuda mais, você limita o contrato dessa função pra só dois argumentos possíveis. 


Alguém que leia o contrato da sua função como está pode entender e aparecer no seu código umas `function(-135)` ou `function(15363)`

2023-07-07 07:25 UTC, Derecky commented on src/components/slider/Carousel.tsx
> +    onSwipedLeft: () => handleSwipe(-1),
Aqui pode aparecer esses `handleswipe(-2736)` como comentei

2023-07-07 07:25 UTC, Derecky commented on src/components/slider/Carousel.tsx
> +}
Esse conteúdo pode ser exportado de outro arquivo, como um `carousel.types.ts`

2023-07-07 07:25 UTC, Derecky commented on src/components/slider/Carousel.tsx
> +]
Todo esse conteúdo aqui pode ser exportado de um arquivo `carousel.constants.ts`

2023-07-07 07:25 UTC, Derecky commented on src/components/slider/Carousel.tsx
> +  const currentItem = slidesData[activeIndex]
Todo esse conteúdo deste arquivo, até aqui, concorda que tem mais a ver com o comportamento que com a renderização? Aqui vou dar uma sugestão pra ti de um pattern, que no momento não lembro o nome, mas a ideia é separar o que é renderização do componente do que é comportamento, responsabilidade única pro arquivo. 

Todo esse código até aqui, poderia ser exportado de um hook (lembrando que todo hook deve começar com `use`, nesse caso poderia ser `useCarousel`)

Poderia ser o arquivo `carousel.hook.ts` e esse arquivo exporta seu `useCarousel` que exporta um objeto com os dados que você precisa exemplo

```Javascript
return {
  swipeHandlers,
  currentItem,
  ...
}
```

2023-07-11 20:18 UTC, Derecky requested changes
só alguns apontamentos

2023-07-11 20:18 UTC, Derecky commented on src/components/carousel/carousel.tsx
> +  const { currentItem, swipeHandlers, setActiveIndex } = useCarousel(slidesData)
esse ```slidesData``` não precisa estar passando aqui pra o carousel, você pode consumir ele já dentro do próprio hook, é uma constante

2023-07-11 20:18 UTC, Derecky commented on src/components/carousel/carousel.hook.ts
> +  }
acho que essa lógica está um tanto confusa, não seria algo do tipo:

```suggestion
  const handleSwipe = (updateCount: UPDATE_COUNT) => {
    if (updateCount === UPDATE_COUNT.DECREMENT ) {
      activeIndex === 0 ? 
        setActiveIndex(() => slidesData.length - 1) :
        setActiveIndex(oldIndexState => oldIndexState - 1)
    } else {
      activeIndex === slidesData.length - 1 ? 
        setActiveIndex(0) :
        setActiveIndex(oldIndexState => oldIndexState + 1)
    }
  }
```

2023-07-13 18:22 UTC, xnd-dev commented on src/components/carousel/carousel.tsx
> +  const { currentItem, swipeHandlers, setActiveIndex } = useCarousel(slidesData)
Arrumei

2023-07-13 18:22 UTC, xnd-dev commented on src/components/carousel/carousel.hook.ts
> +  }
Arrumei

2023-07-19 14:39 UTC, Felipee-M approved these changes, later dismissed
Ok.

2023-07-23 19:04 UTC, Derecky approved these changes, later dismissed

2023-07-31 21:52 UTC, Felipee-M approved these changes

2023-08-01 01:56 UTC, merged