feature: Creation of CTA section
xnd-dev/ipas pull request #13
Opened 2023-07-17 21:20 UTC by Felipee-M

## Purpose

Creation of CTA(Call to Action) section.

## Approach and changes

Creation of CTA section, using same base of the hero banner, just adjusting some measures to match with figma layout.

## Definition of done

- [x ] Behavior reviewed
- [ x] Development completed
- [x ] Reviewers assigned

## Screenshots

![image](https://github.com/xnd-dev/ipas/assets/71663097/73f629a0-d768-444b-818f-4938d210d07c)

2023-07-19 03:51 UTC, xnd-dev requested changes
Duas revisões bem pequenas, uma sobre o chamado da função e outra sobre o id dessa section

2023-07-19 03:51 UTC, xnd-dev commented on src/components/cta/cta.tsx
Achei muito estranho a função utilizando sigla em minúsculo "Cta( )", se tu for usar sigla na function acho que ficaria melhor tudo em maiúsculo = CTA( ), ou coloca a palavra toda em CamelCase = CallToAction( )

2023-07-19 03:51 UTC, xnd-dev commented on src/components/cta/cta.tsx
> +      <S.SectionContainer id="06">
nomeia o id da section igual ao id que ta no nav, essa daí ta como "seja-um-vonluntario"

2023-07-19 14:51 UTC, Felipee-M commented on src/components/cta/cta.tsx
Ajustado.

2023-07-19 14:51 UTC, Felipee-M commented on src/components/cta/cta.tsx
> +      <S.SectionContainer id="06">
Ajustado.

2023-07-20 21:04 UTC, xnd-dev approved these changes
lgtm

2023-07-23 19:04 UTC, Derecky approved these changes

2023-07-25 13:41 UTC, merged