feat: Creation of the Footer
xnd-dev/ipas pull request #14
Opened 2023-07-17 23:01 UTC by Felipee-M

## Purpose

Creation of the footer.

## Approach and changes

Creation of the footer with header bases, just adjusting some details to match with the figma.

## Definition of done

- [x ] Behavior reviewed
- [ x] Development completed
- [x ] Reviewers assigned

## Screenshots

![image](https://github.com/xnd-dev/ipas/assets/71663097/a97bf8e8-18e5-433c-aa36-117df1f70e4c)

2023-07-19 03:41 UTC, xnd-dev requested changes
Fiz pequenos apontamentos sobre a página de estilos e a interação dos contatos do footer

2023-07-19 03:41 UTC, xnd-dev commented on src/components/footer/footer.styles.ts
Pq no teus estilos do footer tem um "HeaderContainer"? Não seria talvez um "FooterContainer"?

2023-07-19 03:41 UTC, xnd-dev commented on src/components/footer/footer.tsx
O e-mail não deveria ser um link com o href com um mailto:contato@ipas.com?
E o telefone um link para abrir o número href="tel:+5582996621031"?
Da mesma forma você pode linkar os logos das rede sociais aos seus respectivos links.

2023-07-19 15:34 UTC, Felipee-M commented on src/components/footer/footer.styles.ts
fixed.

2023-07-19 15:34 UTC, Felipee-M commented on src/components/footer/footer.tsx
fixed

2023-07-20 21:03 UTC, xnd-dev submitted a review, later dismissed
lgtm

2023-07-23 19:05 UTC, Derecky approved these changes, later dismissed

2023-07-25 16:21 UTC, xnd-dev approved these changes
lgtm

2023-07-25 16:22 UTC, merged