Criação das duas seções do meio do site
xnd-dev/ipas pull request #25
Opened 2023-10-09 00:44 UTC by Hime-chan

## Purpose

Criação do componente para o "Nossos Projetos" e "Ações voluntárias". 

## Approach and changes

- O componente "gallery-columns" foi criado. Esse componente é responsável por organizar as fotos do componente "projects-overview" em 4 colunas, das quais a primeira e a última têm apenas 2 fotos e as do meio têm 4 fotos. As fotos são recebidas por parâmetro em um vetor bidimensional.
- O componente "projects-overview" imprime as duas seções do meio do site. Ele mesmo reorganiza os campos (já que na versão mobile, a ordem das coisas é bem diferente) usando javascript. O estilo é modificado usando o próprio css.
- Optei por fazer a versão mobile usando porcentagem da largura do celular, pra não ficar muito pequeno em celulares grandes ou muito grande em celulares pequenos. Usei "vw" e calculei a porcentagem de forma que ficasse coerente com o do figma.

## Definition of done

- [ ] Behavior reviewed
- [ ] Development completed
- [ ] Reviewers assigned
- [ ] Unit and integration tests

## Screenshots

Versão pc:
![image](https://github.com/xnd-dev/ipas/assets/16924515/22a107f6-603a-48cf-9d14-a1b5ec48701b)
Versão mobile:
![image](https://github.com/xnd-dev/ipas/assets/16924515/ef209a1d-66f6-42a8-984c-58abf3a864bb)
![image](https://github.com/xnd-dev/ipas/assets/16924515/73bc26f1-cd71-4e5a-ab89-05b0f83259da)
(Obs.: A seção anterior está invadindo a seção que acabei de fazer porque ainda é a da V4)

2023-10-10 17:06 UTC, Derecky requested changes

2023-10-10 17:06 UTC, Derecky commented on src/components/gallery-columns/gallery-columns.styles.ts
> +  '@media (max-width: 768px)': {
Tem um breakpoint do stitches `@sm`

2023-10-10 17:06 UTC, Derecky commented on src/components/projects-overview/projects-overview.constants.ts
> +    fotos: [['projetos_col1_lin1.png', 'projetos_col1_lin2.png'],
rodando o lint, acho que a identação mudaria aqui

2023-10-10 17:06 UTC, Derecky commented on src/components/projects-overview/projects-overview.constants.ts
> +    fotos: [['acoesvol_col1_lin1.png', 'acoesvol_col1_lin2.png'],
aqui também.

roda `yarn lint` no terminal

2023-10-10 17:06 UTC, Derecky commented on src/components/projects-overview/projects-overview.styles.ts
> +  '@media (max-width: 768px)': {
`@sm`

2023-10-10 17:06 UTC, Derecky commented on src/components/projects-overview/projects-overview.styles.ts
> +  '@media (max-width: 768px)': {
`@sm`

2023-10-10 17:06 UTC, Derecky commented on src/components/projects-overview/projects-overview.styles.ts
> +export const SectionSecao = styled('section', {
O nome dessa variável ficou um tanto confuso `SectionSecao`

2023-10-10 17:06 UTC, Derecky commented on src/components/projects-overview/projects-overview.tsx
> +        </S.SectionSecao>
Esse trecho está bastante confuso, com bastante condicional dentro. Será que não daria pra quebrar em sub componentes?

2023-10-10 17:06 UTC, Derecky commented on src/components/projects-overview/projects-overview.types.ts
> +  fotos: string[][]
preserva as variáveis em inglês :3

2023-10-10 17:06 UTC, Derecky commented on src/components/projects-overview/projects-overview.styles.ts
> +  '@media (max-width: 768px)': {
`@sm`

2023-10-10 17:06 UTC, Derecky commented on src/components/projects-overview/projects-overview.styles.ts
> +  '@media (max-width: 768px)': {
`@sm`

2023-10-15 21:18 UTC, Hime-chan commented on src/components/gallery-columns/gallery-columns.styles.ts
> +  '@media (max-width: 768px)': {
Feito 😸 Consegui com sua ajuda! 
Ps.: Vou colocar o 👍 em todos os comentários sobre essa mesma alteração

2023-10-15 21:21 UTC, Derecky approved these changes

2023-10-15 21:21 UTC, Hime-chan commented on src/components/projects-overview/projects-overview.constants.ts
> +    fotos: [['projetos_col1_lin1.png', 'projetos_col1_lin2.png'],
Instalei o lint no projeto e baixei a extensão dele, mas não consegui fazer funcionar quando eu salvo o arquivo. Quando eu tento fazer manualmente com o Ctrl+Alt+P >> EstLint: , ele diz que "Failed to apply ESLint fixes to the document. Please consider opening an issue with steps to reproduce." Não sei bem como abrir um chamado/issue, então acho que fiquei sem lint... Mas, pelo que entendi, instalei no projeto.

2023-10-15 21:22 UTC, Hime-chan commented on src/components/projects-overview/projects-overview.styles.ts
> +export const SectionSecao = styled('section', {
Corrigido! XD Desculpa pela sintaxe horrível.. Agora acho que ficou bem organizado

2023-10-15 21:23 UTC, Hime-chan commented on src/components/projects-overview/projects-overview.tsx
> +        </S.SectionSecao>
Feito :) Criei uma função pra reordenar os elementos de acordo com um vetor com as posições de cada um passado de parâmetro

2023-10-15 21:23 UTC, Hime-chan commented on src/components/projects-overview/projects-overview.types.ts
> +  fotos: string[][]
Corrigido :D

2023-10-15 21:33 UTC, merged