Section1
xnd-dev/ipas pull request #8
Opened 2023-06-29 01:58 UTC by xnd-dev

## Purpose

Create the first section of the site.

## Approach and changes

Creation and stylization of the first section.

## Definition of done

- [x] Behavior reviewed
- [x] Development completed
- [x] Reviewers assigned

## Screenshots
![image](https://github.com/xnd-dev/ipas/assets/102488612/8e61d0c2-d925-4b79-937b-fe527a904564)

2023-06-29 17:52 UTC, Felipee-M submitted a review, later dismissed
Nothing to add.

2023-06-29 21:06 UTC, Derecky commented on src/components/first-section/first-section.styles.ts
> +  // flexShrink: 0,
pode remover o comentário

2023-06-29 21:06 UTC, Derecky commented on src/components/first-section/first-section.tsx
> +          <div>
renderizar texto direto dentro de div não é uma boa prática

2023-06-29 21:17 UTC, Derecky requested changes
Alguns ajustes aí pra fazer, e algumas sugestões

2023-06-29 21:17 UTC, Derecky commented on src/components/first-section/first-section.tsx
> +          Junte-se a nós nessa jornada de transformação social e faça parte do
Encapsula esse texto com tags de texto p, h1, h2, h3, etc...

2023-06-29 21:17 UTC, Derecky commented on src/components/first-section/first-section.tsx
> +          Doe agora <HandCoins size={16} />{' '}
porque adição de espaço após o ícone? alinha com padding

2023-06-29 21:17 UTC, Derecky commented on src/components/first-section/first-section.styles.ts
Ao invés de dividir o nome com section1, section2, section3, é bom nomear o componente com o que ele fez, fica mais fácil a comunicação com o resto to time do que falando section01, as sections podem mudar de posição em algum momento e o trabalho de renomear será maior

2023-06-29 21:17 UTC, Derecky commented on src/components/first-section/first-section.tsx
> +import {
Só sugestão, para não sujar demais os imports poderia subir como
```suggestion
import * as S from './first-section.styles'
```

Ajuda caso os ux comecem a seccionar mais internamente

2023-06-29 21:17 UTC, Derecky commented on src/pages/index.tsx
> +import { Section1 } from '@/components/first-section/first-section'
poderia ter um index dentro dessa pasta exportando o componente e a tipagem dele caso exista

2023-06-29 21:17 UTC, Derecky commented on src/components/first-section/first-section.styles.ts
> +  width: '$176',
Acho que está havendo uma confusão de espaçamento com width e height, são diferentes, espaçamentos são para usar nas distância entre elementos, como margins, paddings, width são variáveis mesmo, se for cadastrar todos de um site, vai precisar de um arquivo de spaces gigantesco

2023-06-29 21:24 UTC, Derecky commented
Outra coisa, senti falta dos breakpoints para a responsividades.

2023-07-01 01:20 UTC, xnd-dev commented on src/components/first-section/first-section.tsx
> +          Doe agora <HandCoins size={16} />{' '}
essa aí foi automática quando dei ctrl + s, nem notei kkkk

2023-07-04 03:14 UTC, Derecky requested changes

2023-07-04 03:14 UTC, Derecky commented on src/components/hero-banner/hero-banner.tsx
> +          <p>
tá renderizando um parágrafo dentro de um h2, a função do parágrafo é ser parágrafo mesmo, pode ser  um span

2023-07-04 03:15 UTC, Derecky commented on src/pages/index.tsx
> +import { Section1 } from '@/components/first-section/first-section'
faltou essa aqui

2023-07-04 19:58 UTC, xnd-dev commented on src/components/hero-banner/hero-banner.tsx
> +          <p>
é que eu precisava que a próxima palavra ficasse em baixo

2023-07-07 07:28 UTC, Derecky submitted a review, later dismissed
Lgtm

2023-07-09 21:49 UTC, Felipee-M approved these changes
Safe to push.

2023-07-09 21:53 UTC, merged